version: '3'

services:
  server:
    image: groupe_b_9/server:latest
    build:
      context: ./IoT-Gateway/
      dockerfile: Dockerfile
    container_name : server
    environment:
      - client=client

  client:
    image: groupe_b_9/sensor:latest
    build:
      context: ./Sensor/
      dockerfile: Dockerfile
    container_name: client
    environment:
      - DESTINATION=server




