version: '3'

services:
  iot:
    image: groupe_b_9/server:latest
    build:
      context: ./IoT-Gateway/
      dockerfile: Dockerfile
    container_name : IotGateway
    environment:
      NUMBERPORTS: "4"


  sensor1:
    image: groupe_b_9/sensor:latest
    build:
      context: ./Sensor/
      dockerfile: Dockerfile
    container_name: Sensor1
    environment:
       DESTINATION: "iot"
       SENSOR_NAME: "Heizung Wohnzimmer"
       SENSOR_TYPE: "Temperatur"
       SENSOR_ID: "1"

  sensor2:
    image: groupe_b_9/sensor:latest

    build:
     context: ./Sensor/
     dockerfile: Dockerfile
    container_name: Sensor2
    environment:
     DESTINATION: "iot"
     SENSOR_NAME: "Dachterrasse"
     SENSOR_TYPE: "Helligkeit"
     SENSOR_ID: "2"

  sensor3:
    image: groupe_b_9/sensor:latest

    build:
      context: ./Sensor/
      dockerfile: Dockerfile
    container_name: Sensor3
    environment:
      DESTINATION: "iot"
      SENSOR_NAME: "Dachterrasse"
      SENSOR_TYPE: "Niederschlag"
      SENSOR_ID: "3"

  sensor4:
    image: groupe_b_9/sensor:latest

    build:
      context: ./Sensor/
      dockerfile: Dockerfile
    container_name: Sensor4
    environment:
      DESTINATION: "iot"
      SENSOR_NAME: "Dach"
      SENSOR_TYPE: "Wind"
      SENSOR_ID: "4"




