version: '3'

services:
  Database:
    image: groupe_b_9/database:latest
    build:
      context: ./Database/
      dockerfile: Dockerfile
    container_name: Database
    environment:
      DATABASENAME: "DATABASE1"


  Database2:
    image: groupe_b_9/database2:latest
    build:
      context: ./Database/
      dockerfile: Dockerfile
    container_name: Database2
    environment:
      DATABASENAME: "DATABASE2"

  iot:
    image: groupe_b_9/server:latest
    build:
      context: ./IoT-Gateway/
      dockerfile: Dockerfile
    container_name : IotGateway
    depends_on:
      - "HTTPserver"
    volumes:
      - ./sharedFolder:/sharedData/RTT

    environment:
      NUMBEROFSENSORS: "4"
      DESTINATIONTCP: "HTTPserver"


  sensor1:
    image: groupe_b_9/sensor:latest
    build:
      context: ./Sensor/
      dockerfile: Dockerfile
    container_name: Sensor1
    depends_on:
      - "HTTPserver"
    environment:
       DESTINATION: "iot"
       SENSOR_NAME: "Heizung Wohnzimmer"
       SENSOR_TYPE: "Temperatur"
       SENSOR_ID: "1"

  sensor2:
    image: groupe_b_9/sensor:latest

    build:
     context: ./Sensor/
     dockerfile: Dockerfile
    container_name: Sensor2
    depends_on:
      - "HTTPserver"
    environment:
     DESTINATION: "iot"
     SENSOR_NAME: "Balkon"
     SENSOR_TYPE: "Helligkeit"
     SENSOR_ID: "2"

  sensor3:
    image: groupe_b_9/sensor:latest

    build:
      context: ./Sensor/
      dockerfile: Dockerfile
    container_name: Sensor3
    depends_on:
      - "HTTPserver"
    environment:
      DESTINATION: "iot"
      SENSOR_NAME: "Garten"
      SENSOR_TYPE: "Niederschlag"
      SENSOR_ID: "3"

  sensor4:
    image: groupe_b_9/sensor:latest

    build:
      context: ./Sensor/
      dockerfile: Dockerfile
    depends_on:
        - "HTTPserver"
    container_name: Sensor4
    environment:
      DESTINATION: "iot"
      SENSOR_NAME: "Dach"
      SENSOR_TYPE: "Wind"
      SENSOR_ID: "4"

  HTTPserver:
    image: groupe_b_9/httpserver:latest

    build:
      context: ./HTTP-Server/
      dockerfile: Dockerfile
    container_name: HTTP-Server
    environment:
       DESTINATIONTCP: "iot"
    depends_on:
      - "Database"


  mosquitto:
    image: "eclipse-mosquitto"
    container_name: "mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./sharedFolder/mosquitto.conf:/mosquitto/config/mosquitto.conf


  sensor5:
    image: groupe_b_9/mqttsensor:latest
    build:
      context: ./MQTTSensor/
      dockerfile: Dockerfile
    container_name: Sensor5
    depends_on:
      - mosquitto
    environment:
      SENSOR_NAME: "Heizung Schlafzimmer"
      SENSOR_TYPE: "Temperatur"
      SENSOR_ID: "5"

  sensor6:
    image: groupe_b_9/mqttsensor:latest

    build:
      context: ./MQTTSensor/
      dockerfile: Dockerfile
    container_name: Sensor6
    depends_on:
      - mosquitto
    environment:

      SENSOR_NAME: "Dachterasse"
      SENSOR_TYPE: "Helligkeit"
      SENSOR_ID: "6"

  sensor7:
    image: groupe_b_9/mqttsensor:latest

    build:
      context: ./MQTTSensor/
      dockerfile: Dockerfile
    container_name: Sensor7
    depends_on:
      - mosquitto
    environment:
      SENSOR_NAME: "Dach"
      SENSOR_TYPE: "Niederschlag"
      SENSOR_ID: "7"

  sensor8:
    image: groupe_b_9/mqttsensor:latest

    build:
      context: ./MQTTSensor/
      dockerfile: Dockerfile

    container_name: Sensor8
    depends_on:
      - mosquitto
    environment:
      SENSOR_NAME: "Teich"
      SENSOR_TYPE: "Wind"
      SENSOR_ID: "8"


  MQTTAdapter:
      image: groupe_b_9/mqttadapter:latest

      build:
          context: ./MQTTAdapter/
          dockerfile: Dockerfile
      container_name: MQTTAdapter
      depends_on:
        - mosquitto
      environment:
        DESTINATION: "iot"

