version: '3'

services:
  server:
    image: "server"
    build:
      context: ./IoT-Gateway/
      dockerfile: Dockerfile
    container_name : server
    environment:
      - client=client

  client:
    image: "client"
    build:
      context: ./Sensor/
      dockerfile: Dockerfile
    container_name: client
    environment:
      - DESTINATION=server


